//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a2pt1console.GetWebContent {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetWebContent.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWebContent", ReplyAction="http://tempuri.org/IService/GetWebContentResponse")]
        a2pt1console.GetWebContent.GetWebContentResponse GetWebContent(a2pt1console.GetWebContent.GetWebContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWebContent", ReplyAction="http://tempuri.org/IService/GetWebContentResponse")]
        System.Threading.Tasks.Task<a2pt1console.GetWebContent.GetWebContentResponse> GetWebContentAsync(a2pt1console.GetWebContent.GetWebContentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWebContent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWebContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string url;
        
        public GetWebContentRequest() {
        }
        
        public GetWebContentRequest(string url) {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWebContentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWebContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetWebContentResult;
        
        public GetWebContentResponse() {
        }
        
        public GetWebContentResponse(string GetWebContentResult) {
            this.GetWebContentResult = GetWebContentResult;
        }
    }
}
